---
run:
  name: 2025-11-06_penn
  description: full run of recent Pennsylvania samples
  technician: Cob Staines
  runDir: runs/2025-11-06_penn
  qiimeEnv: qiime2-amplicon-2025.4
taxonomy:
  classifierDir: vertebrata16s_classifier
  updateBool: false
trimPaired:              # trim primers
  errorRate: 0.3         # error rate for trimming of primers
denoisePaired:           # denoise
  truncQ: 2              # quality threshold at which to truncate reads
  truncLen: 0            # length at which to truncate reads (forward and reverse)
vsearchGlobal:
  maxaccepts: 20          # maximum number of hits to accept
  percIdentity: 0.7      # minimum identity for hit acceptance
  queryCov: 0.7          # minimum query coverage hit acceptance
