---
run:
  name: methods_2025-12-29
  runDir: runs/methods_2025-12-29
  description: Methods comparison run, including all samples from February and December 2023 Illumina sequencing
  technician: Cob Staines
  qiimeEnv: qiime2-amplicon-2025.4
taxonomy:
  classifierDir: vertebrata16s_classifier
  updateBool: false
trimPaired:              # trim primers
  errorRate: 0.3         # error rate for trimming of primers
denoisePaired:           # denoise
  truncQ: 2              # quality threshold at which to truncate reads
  truncLen: 0            # length at which to truncate reads (forward and reverse)
consensusBlast:
  maxaccepts: 10         # maximum number of hits to accept
  percIdentity: 0.98     # minimum identity for hit acceptance
  queryCov: 0.95         # minimum query coverage hit acceptance
vsearchGlobal:
  maxaccepts: 20         # maximum number of hits to accept
  percIdentity: 0.5      # minimum identity for hit acceptance
  queryCov: 0.5          # minimum query coverage hit acceptance
geography:
  run_gbif_lookup: true
  run_iucn_lookup: true
  country_codes:
    - "PA"
    - "US"
